# Generated by Django 5.0.2 on 2024-02-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='filename',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
